// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sd_set_progress_file
void sd_set_progress_file(std::string path);
RcppExport SEXP _sd2R_sd_set_progress_file(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    sd_set_progress_file(path);
    return R_NilValue;
END_RCPP
}
// sd_meta_backend_available
bool sd_meta_backend_available();
RcppExport SEXP _sd2R_sd_meta_backend_available() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(sd_meta_backend_available());
    return rcpp_result_gen;
END_RCPP
}
// sd_clear_progress_file
void sd_clear_progress_file();
RcppExport SEXP _sd2R_sd_clear_progress_file() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    sd_clear_progress_file();
    return R_NilValue;
END_RCPP
}
// sd_set_preview_dump
void sd_set_preview_dump(std::string path, std::string mode, int interval, bool denoised, bool noisy);
RcppExport SEXP _sd2R_sd_set_preview_dump(SEXP pathSEXP, SEXP modeSEXP, SEXP intervalSEXP, SEXP denoisedSEXP, SEXP noisySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< int >::type interval(intervalSEXP);
    Rcpp::traits::input_parameter< bool >::type denoised(denoisedSEXP);
    Rcpp::traits::input_parameter< bool >::type noisy(noisySEXP);
    sd_set_preview_dump(path, mode, interval, denoised, noisy);
    return R_NilValue;
END_RCPP
}
// sd_clear_preview_dump
void sd_clear_preview_dump();
RcppExport SEXP _sd2R_sd_clear_preview_dump() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    sd_clear_preview_dump();
    return R_NilValue;
END_RCPP
}
// sd_set_log_file
void sd_set_log_file(std::string path);
RcppExport SEXP _sd2R_sd_set_log_file(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    sd_set_log_file(path);
    return R_NilValue;
END_RCPP
}
// sd_set_log_debug
void sd_set_log_debug(bool enabled);
RcppExport SEXP _sd2R_sd_set_log_debug(SEXP enabledSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type enabled(enabledSEXP);
    sd_set_log_debug(enabled);
    return R_NilValue;
END_RCPP
}
// sd_clear_log_file
void sd_clear_log_file();
RcppExport SEXP _sd2R_sd_clear_log_file() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    sd_clear_log_file();
    return R_NilValue;
END_RCPP
}
// sd_set_verbose
void sd_set_verbose(bool verbose);
RcppExport SEXP _sd2R_sd_set_verbose(SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    sd_set_verbose(verbose);
    return R_NilValue;
END_RCPP
}
// sd_profile_start
void sd_profile_start();
RcppExport SEXP _sd2R_sd_profile_start() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    sd_profile_start();
    return R_NilValue;
END_RCPP
}
// sd_profile_stop
void sd_profile_stop();
RcppExport SEXP _sd2R_sd_profile_stop() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    sd_profile_stop();
    return R_NilValue;
END_RCPP
}
// sd_profile_get
Rcpp::DataFrame sd_profile_get();
RcppExport SEXP _sd2R_sd_profile_get() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(sd_profile_get());
    return rcpp_result_gen;
END_RCPP
}
// sd_init_log
void sd_init_log();
RcppExport SEXP _sd2R_sd_init_log() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    sd_init_log();
    return R_NilValue;
END_RCPP
}
// sd_create_context
SEXP sd_create_context(Rcpp::List params);
RcppExport SEXP _sd2R_sd_create_context(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_create_context(params));
    return rcpp_result_gen;
END_RCPP
}
// sd_destroy_context_impl
void sd_destroy_context_impl(SEXP ctx_sexp);
RcppExport SEXP _sd2R_sd_destroy_context_impl(SEXP ctx_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ctx_sexp(ctx_sexpSEXP);
    sd_destroy_context_impl(ctx_sexp);
    return R_NilValue;
END_RCPP
}
// sd_create_context_async
bool sd_create_context_async(Rcpp::List params);
RcppExport SEXP _sd2R_sd_create_context_async(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_create_context_async(params));
    return rcpp_result_gen;
END_RCPP
}
// sd_create_context_poll
Rcpp::List sd_create_context_poll();
RcppExport SEXP _sd2R_sd_create_context_poll() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(sd_create_context_poll());
    return rcpp_result_gen;
END_RCPP
}
// sd_create_context_result
SEXP sd_create_context_result();
RcppExport SEXP _sd2R_sd_create_context_result() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(sd_create_context_result());
    return rcpp_result_gen;
END_RCPP
}
// sd_ctx_version_cpp
int sd_ctx_version_cpp(SEXP ctx_sexp);
RcppExport SEXP _sd2R_sd_ctx_version_cpp(SEXP ctx_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ctx_sexp(ctx_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_ctx_version_cpp(ctx_sexp));
    return rcpp_result_gen;
END_RCPP
}
// sd_ctx_supports_ref_cpp
bool sd_ctx_supports_ref_cpp(SEXP ctx_sexp);
RcppExport SEXP _sd2R_sd_ctx_supports_ref_cpp(SEXP ctx_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ctx_sexp(ctx_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_ctx_supports_ref_cpp(ctx_sexp));
    return rcpp_result_gen;
END_RCPP
}
// sd_encode_text_cpp
SEXP sd_encode_text_cpp(SEXP ctx_sexp, std::string prompt, int clip_skip, int width, int height);
RcppExport SEXP _sd2R_sd_encode_text_cpp(SEXP ctx_sexpSEXP, SEXP promptSEXP, SEXP clip_skipSEXP, SEXP widthSEXP, SEXP heightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ctx_sexp(ctx_sexpSEXP);
    Rcpp::traits::input_parameter< std::string >::type prompt(promptSEXP);
    Rcpp::traits::input_parameter< int >::type clip_skip(clip_skipSEXP);
    Rcpp::traits::input_parameter< int >::type width(widthSEXP);
    Rcpp::traits::input_parameter< int >::type height(heightSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_encode_text_cpp(ctx_sexp, prompt, clip_skip, width, height));
    return rcpp_result_gen;
END_RCPP
}
// sd_encode_image_cpp
SEXP sd_encode_image_cpp(SEXP ctx_sexp, Rcpp::List image);
RcppExport SEXP _sd2R_sd_encode_image_cpp(SEXP ctx_sexpSEXP, SEXP imageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ctx_sexp(ctx_sexpSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type image(imageSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_encode_image_cpp(ctx_sexp, image));
    return rcpp_result_gen;
END_RCPP
}
// sd_decode_latent_cpp
Rcpp::List sd_decode_latent_cpp(SEXP ctx_sexp, SEXP latent);
RcppExport SEXP _sd2R_sd_decode_latent_cpp(SEXP ctx_sexpSEXP, SEXP latentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ctx_sexp(ctx_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type latent(latentSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_decode_latent_cpp(ctx_sexp, latent));
    return rcpp_result_gen;
END_RCPP
}
// sd_sample_cpp
SEXP sd_sample_cpp(SEXP ctx_sexp, SEXP init_latent, SEXP noise, Rcpp::List cond, Rcpp::List uncond, int sample_method, int scheduler, int sample_steps, double cfg_scale, double eta, double strength, Rcpp::Nullable<Rcpp::NumericVector> custom_sigmas);
RcppExport SEXP _sd2R_sd_sample_cpp(SEXP ctx_sexpSEXP, SEXP init_latentSEXP, SEXP noiseSEXP, SEXP condSEXP, SEXP uncondSEXP, SEXP sample_methodSEXP, SEXP schedulerSEXP, SEXP sample_stepsSEXP, SEXP cfg_scaleSEXP, SEXP etaSEXP, SEXP strengthSEXP, SEXP custom_sigmasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ctx_sexp(ctx_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type init_latent(init_latentSEXP);
    Rcpp::traits::input_parameter< SEXP >::type noise(noiseSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type cond(condSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type uncond(uncondSEXP);
    Rcpp::traits::input_parameter< int >::type sample_method(sample_methodSEXP);
    Rcpp::traits::input_parameter< int >::type scheduler(schedulerSEXP);
    Rcpp::traits::input_parameter< int >::type sample_steps(sample_stepsSEXP);
    Rcpp::traits::input_parameter< double >::type cfg_scale(cfg_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type strength(strengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type custom_sigmas(custom_sigmasSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_sample_cpp(ctx_sexp, init_latent, noise, cond, uncond, sample_method, scheduler, sample_steps, cfg_scale, eta, strength, custom_sigmas));
    return rcpp_result_gen;
END_RCPP
}
// sd_sampler_sigmas_cpp
Rcpp::NumericVector sd_sampler_sigmas_cpp(SEXP ctx_sexp, int scheduler, int sample_method, int sample_steps, int width, int height);
RcppExport SEXP _sd2R_sd_sampler_sigmas_cpp(SEXP ctx_sexpSEXP, SEXP schedulerSEXP, SEXP sample_methodSEXP, SEXP sample_stepsSEXP, SEXP widthSEXP, SEXP heightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ctx_sexp(ctx_sexpSEXP);
    Rcpp::traits::input_parameter< int >::type scheduler(schedulerSEXP);
    Rcpp::traits::input_parameter< int >::type sample_method(sample_methodSEXP);
    Rcpp::traits::input_parameter< int >::type sample_steps(sample_stepsSEXP);
    Rcpp::traits::input_parameter< int >::type width(widthSEXP);
    Rcpp::traits::input_parameter< int >::type height(heightSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_sampler_sigmas_cpp(ctx_sexp, scheduler, sample_method, sample_steps, width, height));
    return rcpp_result_gen;
END_RCPP
}
// sd_sampler_begin_cpp
void sd_sampler_begin_cpp(SEXP ctx_sexp);
RcppExport SEXP _sd2R_sd_sampler_begin_cpp(SEXP ctx_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ctx_sexp(ctx_sexpSEXP);
    sd_sampler_begin_cpp(ctx_sexp);
    return R_NilValue;
END_RCPP
}
// sd_sampler_end_cpp
void sd_sampler_end_cpp(SEXP ctx_sexp);
RcppExport SEXP _sd2R_sd_sampler_end_cpp(SEXP ctx_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ctx_sexp(ctx_sexpSEXP);
    sd_sampler_end_cpp(ctx_sexp);
    return R_NilValue;
END_RCPP
}
// sd_noise_scale_cpp
SEXP sd_noise_scale_cpp(SEXP ctx_sexp, SEXP init_latent, SEXP noise, double sigma0);
RcppExport SEXP _sd2R_sd_noise_scale_cpp(SEXP ctx_sexpSEXP, SEXP init_latentSEXP, SEXP noiseSEXP, SEXP sigma0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ctx_sexp(ctx_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type init_latent(init_latentSEXP);
    Rcpp::traits::input_parameter< SEXP >::type noise(noiseSEXP);
    Rcpp::traits::input_parameter< double >::type sigma0(sigma0SEXP);
    rcpp_result_gen = Rcpp::wrap(sd_noise_scale_cpp(ctx_sexp, init_latent, noise, sigma0));
    return rcpp_result_gen;
END_RCPP
}
// sd_inverse_noise_scale_cpp
SEXP sd_inverse_noise_scale_cpp(SEXP ctx_sexp, SEXP x_in, double sigma_last);
RcppExport SEXP _sd2R_sd_inverse_noise_scale_cpp(SEXP ctx_sexpSEXP, SEXP x_inSEXP, SEXP sigma_lastSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ctx_sexp(ctx_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x_in(x_inSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_last(sigma_lastSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_inverse_noise_scale_cpp(ctx_sexp, x_in, sigma_last));
    return rcpp_result_gen;
END_RCPP
}
// sd_denoise_step_cpp
SEXP sd_denoise_step_cpp(SEXP ctx_sexp, SEXP x_in, double sigma, Rcpp::List cond, Rcpp::List uncond, double cfg_scale, int step, int total_steps);
RcppExport SEXP _sd2R_sd_denoise_step_cpp(SEXP ctx_sexpSEXP, SEXP x_inSEXP, SEXP sigmaSEXP, SEXP condSEXP, SEXP uncondSEXP, SEXP cfg_scaleSEXP, SEXP stepSEXP, SEXP total_stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ctx_sexp(ctx_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x_in(x_inSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type cond(condSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type uncond(uncondSEXP);
    Rcpp::traits::input_parameter< double >::type cfg_scale(cfg_scaleSEXP);
    Rcpp::traits::input_parameter< int >::type step(stepSEXP);
    Rcpp::traits::input_parameter< int >::type total_steps(total_stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_denoise_step_cpp(ctx_sexp, x_in, sigma, cond, uncond, cfg_scale, step, total_steps));
    return rcpp_result_gen;
END_RCPP
}
// sd_generate_image
Rcpp::List sd_generate_image(SEXP ctx_sexp, Rcpp::List params);
RcppExport SEXP _sd2R_sd_generate_image(SEXP ctx_sexpSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ctx_sexp(ctx_sexpSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_generate_image(ctx_sexp, params));
    return rcpp_result_gen;
END_RCPP
}
// sd_system_info_cpp
std::string sd_system_info_cpp();
RcppExport SEXP _sd2R_sd_system_info_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(sd_system_info_cpp());
    return rcpp_result_gen;
END_RCPP
}
// sd_version_cpp
std::string sd_version_cpp();
RcppExport SEXP _sd2R_sd_version_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(sd_version_cpp());
    return rcpp_result_gen;
END_RCPP
}
// sd_num_physical_cores_cpp
int sd_num_physical_cores_cpp();
RcppExport SEXP _sd2R_sd_num_physical_cores_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(sd_num_physical_cores_cpp());
    return rcpp_result_gen;
END_RCPP
}
// sd_type_name_cpp
std::string sd_type_name_cpp(int type);
RcppExport SEXP _sd2R_sd_type_name_cpp(SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_type_name_cpp(type));
    return rcpp_result_gen;
END_RCPP
}
// sd_sample_method_name_cpp
std::string sd_sample_method_name_cpp(int method);
RcppExport SEXP _sd2R_sd_sample_method_name_cpp(SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_sample_method_name_cpp(method));
    return rcpp_result_gen;
END_RCPP
}
// sd_scheduler_name_cpp
std::string sd_scheduler_name_cpp(int sched);
RcppExport SEXP _sd2R_sd_scheduler_name_cpp(SEXP schedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type sched(schedSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_scheduler_name_cpp(sched));
    return rcpp_result_gen;
END_RCPP
}
// sd_create_upscaler
SEXP sd_create_upscaler(std::string esrgan_path, int n_threads, bool offload_params_to_cpu, bool direct, int tile_size);
RcppExport SEXP _sd2R_sd_create_upscaler(SEXP esrgan_pathSEXP, SEXP n_threadsSEXP, SEXP offload_params_to_cpuSEXP, SEXP directSEXP, SEXP tile_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type esrgan_path(esrgan_pathSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type offload_params_to_cpu(offload_params_to_cpuSEXP);
    Rcpp::traits::input_parameter< bool >::type direct(directSEXP);
    Rcpp::traits::input_parameter< int >::type tile_size(tile_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_create_upscaler(esrgan_path, n_threads, offload_params_to_cpu, direct, tile_size));
    return rcpp_result_gen;
END_RCPP
}
// sd_upscale
Rcpp::List sd_upscale(SEXP upscaler_sexp, Rcpp::List image, int upscale_factor);
RcppExport SEXP _sd2R_sd_upscale(SEXP upscaler_sexpSEXP, SEXP imageSEXP, SEXP upscale_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type upscaler_sexp(upscaler_sexpSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type image(imageSEXP);
    Rcpp::traits::input_parameter< int >::type upscale_factor(upscale_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_upscale(upscaler_sexp, image, upscale_factor));
    return rcpp_result_gen;
END_RCPP
}
// sd_convert_model
bool sd_convert_model(std::string input_path, std::string output_path, int output_type, std::string vae_path, std::string tensor_type_rules, bool convert_name);
RcppExport SEXP _sd2R_sd_convert_model(SEXP input_pathSEXP, SEXP output_pathSEXP, SEXP output_typeSEXP, SEXP vae_pathSEXP, SEXP tensor_type_rulesSEXP, SEXP convert_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type input_path(input_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type output_path(output_pathSEXP);
    Rcpp::traits::input_parameter< int >::type output_type(output_typeSEXP);
    Rcpp::traits::input_parameter< std::string >::type vae_path(vae_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type tensor_type_rules(tensor_type_rulesSEXP);
    Rcpp::traits::input_parameter< bool >::type convert_name(convert_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_convert_model(input_path, output_path, output_type, vae_path, tensor_type_rules, convert_name));
    return rcpp_result_gen;
END_RCPP
}
// sd_generate_async
bool sd_generate_async(SEXP ctx_sexp, Rcpp::List params);
RcppExport SEXP _sd2R_sd_generate_async(SEXP ctx_sexpSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ctx_sexp(ctx_sexpSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_generate_async(ctx_sexp, params));
    return rcpp_result_gen;
END_RCPP
}
// sd_generate_poll
Rcpp::List sd_generate_poll();
RcppExport SEXP _sd2R_sd_generate_poll() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(sd_generate_poll());
    return rcpp_result_gen;
END_RCPP
}
// sd_generate_result
Rcpp::List sd_generate_result();
RcppExport SEXP _sd2R_sd_generate_result() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(sd_generate_result());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sd2R_sd_set_progress_file", (DL_FUNC) &_sd2R_sd_set_progress_file, 1},
    {"_sd2R_sd_meta_backend_available", (DL_FUNC) &_sd2R_sd_meta_backend_available, 0},
    {"_sd2R_sd_clear_progress_file", (DL_FUNC) &_sd2R_sd_clear_progress_file, 0},
    {"_sd2R_sd_set_preview_dump", (DL_FUNC) &_sd2R_sd_set_preview_dump, 5},
    {"_sd2R_sd_clear_preview_dump", (DL_FUNC) &_sd2R_sd_clear_preview_dump, 0},
    {"_sd2R_sd_set_log_file", (DL_FUNC) &_sd2R_sd_set_log_file, 1},
    {"_sd2R_sd_set_log_debug", (DL_FUNC) &_sd2R_sd_set_log_debug, 1},
    {"_sd2R_sd_clear_log_file", (DL_FUNC) &_sd2R_sd_clear_log_file, 0},
    {"_sd2R_sd_set_verbose", (DL_FUNC) &_sd2R_sd_set_verbose, 1},
    {"_sd2R_sd_profile_start", (DL_FUNC) &_sd2R_sd_profile_start, 0},
    {"_sd2R_sd_profile_stop", (DL_FUNC) &_sd2R_sd_profile_stop, 0},
    {"_sd2R_sd_profile_get", (DL_FUNC) &_sd2R_sd_profile_get, 0},
    {"_sd2R_sd_init_log", (DL_FUNC) &_sd2R_sd_init_log, 0},
    {"_sd2R_sd_create_context", (DL_FUNC) &_sd2R_sd_create_context, 1},
    {"_sd2R_sd_destroy_context_impl", (DL_FUNC) &_sd2R_sd_destroy_context_impl, 1},
    {"_sd2R_sd_create_context_async", (DL_FUNC) &_sd2R_sd_create_context_async, 1},
    {"_sd2R_sd_create_context_poll", (DL_FUNC) &_sd2R_sd_create_context_poll, 0},
    {"_sd2R_sd_create_context_result", (DL_FUNC) &_sd2R_sd_create_context_result, 0},
    {"_sd2R_sd_ctx_version_cpp", (DL_FUNC) &_sd2R_sd_ctx_version_cpp, 1},
    {"_sd2R_sd_ctx_supports_ref_cpp", (DL_FUNC) &_sd2R_sd_ctx_supports_ref_cpp, 1},
    {"_sd2R_sd_encode_text_cpp", (DL_FUNC) &_sd2R_sd_encode_text_cpp, 5},
    {"_sd2R_sd_encode_image_cpp", (DL_FUNC) &_sd2R_sd_encode_image_cpp, 2},
    {"_sd2R_sd_decode_latent_cpp", (DL_FUNC) &_sd2R_sd_decode_latent_cpp, 2},
    {"_sd2R_sd_sample_cpp", (DL_FUNC) &_sd2R_sd_sample_cpp, 12},
    {"_sd2R_sd_sampler_sigmas_cpp", (DL_FUNC) &_sd2R_sd_sampler_sigmas_cpp, 6},
    {"_sd2R_sd_sampler_begin_cpp", (DL_FUNC) &_sd2R_sd_sampler_begin_cpp, 1},
    {"_sd2R_sd_sampler_end_cpp", (DL_FUNC) &_sd2R_sd_sampler_end_cpp, 1},
    {"_sd2R_sd_noise_scale_cpp", (DL_FUNC) &_sd2R_sd_noise_scale_cpp, 4},
    {"_sd2R_sd_inverse_noise_scale_cpp", (DL_FUNC) &_sd2R_sd_inverse_noise_scale_cpp, 3},
    {"_sd2R_sd_denoise_step_cpp", (DL_FUNC) &_sd2R_sd_denoise_step_cpp, 8},
    {"_sd2R_sd_generate_image", (DL_FUNC) &_sd2R_sd_generate_image, 2},
    {"_sd2R_sd_system_info_cpp", (DL_FUNC) &_sd2R_sd_system_info_cpp, 0},
    {"_sd2R_sd_version_cpp", (DL_FUNC) &_sd2R_sd_version_cpp, 0},
    {"_sd2R_sd_num_physical_cores_cpp", (DL_FUNC) &_sd2R_sd_num_physical_cores_cpp, 0},
    {"_sd2R_sd_type_name_cpp", (DL_FUNC) &_sd2R_sd_type_name_cpp, 1},
    {"_sd2R_sd_sample_method_name_cpp", (DL_FUNC) &_sd2R_sd_sample_method_name_cpp, 1},
    {"_sd2R_sd_scheduler_name_cpp", (DL_FUNC) &_sd2R_sd_scheduler_name_cpp, 1},
    {"_sd2R_sd_create_upscaler", (DL_FUNC) &_sd2R_sd_create_upscaler, 5},
    {"_sd2R_sd_upscale", (DL_FUNC) &_sd2R_sd_upscale, 3},
    {"_sd2R_sd_convert_model", (DL_FUNC) &_sd2R_sd_convert_model, 6},
    {"_sd2R_sd_generate_async", (DL_FUNC) &_sd2R_sd_generate_async, 2},
    {"_sd2R_sd_generate_poll", (DL_FUNC) &_sd2R_sd_generate_poll, 0},
    {"_sd2R_sd_generate_result", (DL_FUNC) &_sd2R_sd_generate_result, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_sd2R(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
