# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sd_set_progress_file <- function(path) {
    invisible(.Call(`_sd2R_sd_set_progress_file`, path))
}

sd_clear_progress_file <- function() {
    invisible(.Call(`_sd2R_sd_clear_progress_file`))
}

sd_set_log_file <- function(path) {
    invisible(.Call(`_sd2R_sd_set_log_file`, path))
}

sd_clear_log_file <- function() {
    invisible(.Call(`_sd2R_sd_clear_log_file`))
}

sd_set_verbose <- function(verbose) {
    invisible(.Call(`_sd2R_sd_set_verbose`, verbose))
}

sd_profile_start <- function() {
    invisible(.Call(`_sd2R_sd_profile_start`))
}

sd_profile_stop <- function() {
    invisible(.Call(`_sd2R_sd_profile_stop`))
}

sd_profile_get <- function() {
    .Call(`_sd2R_sd_profile_get`)
}

sd_init_log <- function() {
    invisible(.Call(`_sd2R_sd_init_log`))
}

sd_create_context <- function(params) {
    .Call(`_sd2R_sd_create_context`, params)
}

sd_destroy_context <- function(ctx_sexp) {
    invisible(.Call(`_sd2R_sd_destroy_context`, ctx_sexp))
}

sd_create_context_async <- function(params) {
    .Call(`_sd2R_sd_create_context_async`, params)
}

sd_create_context_poll <- function() {
    .Call(`_sd2R_sd_create_context_poll`)
}

sd_create_context_result <- function() {
    .Call(`_sd2R_sd_create_context_result`)
}

sd_generate_image <- function(ctx_sexp, params) {
    .Call(`_sd2R_sd_generate_image`, ctx_sexp, params)
}

sd_system_info_cpp <- function() {
    .Call(`_sd2R_sd_system_info_cpp`)
}

sd_version_cpp <- function() {
    .Call(`_sd2R_sd_version_cpp`)
}

sd_num_physical_cores_cpp <- function() {
    .Call(`_sd2R_sd_num_physical_cores_cpp`)
}

sd_type_name_cpp <- function(type) {
    .Call(`_sd2R_sd_type_name_cpp`, type)
}

sd_sample_method_name_cpp <- function(method) {
    .Call(`_sd2R_sd_sample_method_name_cpp`, method)
}

sd_scheduler_name_cpp <- function(sched) {
    .Call(`_sd2R_sd_scheduler_name_cpp`, sched)
}

sd_create_upscaler <- function(esrgan_path, n_threads = 0L, offload_params_to_cpu = FALSE, direct = FALSE, tile_size = 0L) {
    .Call(`_sd2R_sd_create_upscaler`, esrgan_path, n_threads, offload_params_to_cpu, direct, tile_size)
}

sd_upscale <- function(upscaler_sexp, image, upscale_factor) {
    .Call(`_sd2R_sd_upscale`, upscaler_sexp, image, upscale_factor)
}

sd_convert_model <- function(input_path, output_path, output_type, vae_path = "", tensor_type_rules = "", convert_name = FALSE) {
    .Call(`_sd2R_sd_convert_model`, input_path, output_path, output_type, vae_path, tensor_type_rules, convert_name)
}

sd_generate_async <- function(ctx_sexp, params) {
    .Call(`_sd2R_sd_generate_async`, ctx_sexp, params)
}

sd_generate_poll <- function() {
    .Call(`_sd2R_sd_generate_poll`)
}

sd_generate_result <- function() {
    .Call(`_sd2R_sd_generate_result`)
}

